/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mDEHsX1J3YSWVvMcFkMkt9

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_8J7GhLNtJ6O4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 8J7ghLNtJ6O4/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_8J7GhLNtJ6O4
});
